name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Verifica build do projeto
        run: |
          cd app  # Navega até a pasta 'app' onde está a solução ou projeto
          dotnet build --configuration Release OrcamentoEletrico.sln  # Compila a solução
